PyAuthGG/Administration.py,sha256=gK8I0grS1kRHmHzyIXYFusR9N8H1LWb2nQPBah2SRJc,3733
PyAuthGG/Application.py,sha256=J9F1DRJk6_xzJFET4lDBy0_EJ0P40dl0ihfH6IsEW68,2868
PyAuthGG/Exceptions.py,sha256=gOeQp--DV-ouJyonestakzVj0xSlJyZjaYYFVHbjTF0,114
PyAuthGG/__init__.py,sha256=VrdxoDkIQGaKrY4emfvLBNUo_4z8wR0CCj2ptwTjMz4,277
PyAuthGG-1.0.4.dist-info/LICENSE.md,sha256=YjpQJBWyP9cAUTHzT47TLN48vMQc2ffkYyLa69QK3Uo,1083
PyAuthGG-1.0.4.dist-info/METADATA,sha256=pF-ST8P5s8k4aGDfIuvWgu-PwyhySHfigVJR8Pn00lk,771
PyAuthGG-1.0.4.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
PyAuthGG-1.0.4.dist-info/top_level.txt,sha256=imSBwuebYLd4JifE0PrULv6ACWY7utZspOpTLfM-COM,9
PyAuthGG-1.0.4.dist-info/RECORD,,
