PyAuthGG/Administration.py,sha256=gK8I0grS1kRHmHzyIXYFusR9N8H1LWb2nQPBah2SRJc,3733
PyAuthGG/Application.py,sha256=P2e1A88eCbKbc-cpGyDR4J7PTIOSuM10xCOIofR4a20,2868
PyAuthGG/Exceptions.py,sha256=gOeQp--DV-ouJyonestakzVj0xSlJyZjaYYFVHbjTF0,114
PyAuthGG/__init__.py,sha256=9i2o9V3lPK1d7ue6MaepH5EQjYIsl8NcFuBPw_ObERA,402
PyAuthGG-1.0.5.dist-info/LICENSE.md,sha256=YjpQJBWyP9cAUTHzT47TLN48vMQc2ffkYyLa69QK3Uo,1083
PyAuthGG-1.0.5.dist-info/METADATA,sha256=V-yjn3e-JJh3lWcJ77vxXeF1Kdq4g9lsiKmPhPcwZ0w,2833
PyAuthGG-1.0.5.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
PyAuthGG-1.0.5.dist-info/top_level.txt,sha256=imSBwuebYLd4JifE0PrULv6ACWY7utZspOpTLfM-COM,9
PyAuthGG-1.0.5.dist-info/RECORD,,
